# SPDX-License-Identifier: PMPL-1.0-or-later

name = "BetLang"
uuid = "b4e71a91-7c3d-4f2b-8e5a-9d6f8b4c1a3e"
authors = ["Jonathan D.A. Jewell <jonathan.jewell@open.ac.uk>"]
version = "0.8.0-dev"
license = "PMPL-1.0-or-later"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.9"
Distributions = "0.25"
StatsBase = "0.34"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
