[package]
name = "bet-check"
description = "Type checker for Betlang"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bet-syntax = { path = "../bet-syntax" }
bet-core = { path = "../bet-core" }
thiserror.workspace = true
