# SPDX-License-Identifier: MIT OR Apache-2.0
name = "Betlang"
uuid = "12345678-1234-1234-1234-123456789abc"
authors = ["Betlang Team"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1.6"
