[package]
name = "bet-rand"
description = "Randomness and distribution primitives for Betlang"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rand.workspace = true
rand_distr.workspace = true
rand_pcg.workspace = true
rand_chacha.workspace = true
